// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// cpp_update_position_inflow
DataFrame cpp_update_position_inflow(double x, double y, double ux, double uy, double up, double K, double dt, std::string drift_destination);
RcppExport SEXP _LPT_cpp_update_position_inflow(SEXP xSEXP, SEXP ySEXP, SEXP uxSEXP, SEXP uySEXP, SEXP upSEXP, SEXP KSEXP, SEXP dtSEXP, SEXP drift_destinationSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type x(xSEXP);
    Rcpp::traits::input_parameter< double >::type y(ySEXP);
    Rcpp::traits::input_parameter< double >::type ux(uxSEXP);
    Rcpp::traits::input_parameter< double >::type uy(uySEXP);
    Rcpp::traits::input_parameter< double >::type up(upSEXP);
    Rcpp::traits::input_parameter< double >::type K(KSEXP);
    Rcpp::traits::input_parameter< double >::type dt(dtSEXP);
    Rcpp::traits::input_parameter< std::string >::type drift_destination(drift_destinationSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_update_position_inflow(x, y, ux, uy, up, K, dt, drift_destination));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_LPT_cpp_update_position_inflow", (DL_FUNC) &_LPT_cpp_update_position_inflow, 8},
    {NULL, NULL, 0}
};

RcppExport void R_init_LPT(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
